home:
    path: /
    controller: App\Controller\HomeController::renderHome

signIn:
    path: /signIn
    controller: App\Controller\UserController::signIn

signUp:
    path: /signUp
    controller: App\Controller\HomeController::renderSignUp

register:
    path: /register
    controller: App\Controller\UserController::registerUser