home:
    path: /
    controller: App\Controller\HomeController::renderHome

signIn:
    path: /signIn
    controller: App\Controller\UserController::signIn

signUp:
    path: /signUp
    controller: App\Controller\HomeController::renderSignUp

register:
    path: /register
    controller: App\Controller\UserController::registerUser

updateProfile:
    path: /updateProfile
    controller: App\Controller\HomeController::renderSignUp

updateUser:
    path: /updateUser
    controller: App\Controller\userController::updateUser

eventCreation:
    path: /eventCreation
    controller: App\Controller\HomeController::renderEventCreation

createEvent:
    path: /createEvent
    controller: App\Controller\EventController::createEvent

editEvent:
    path: /editEvent
    controller: App\Controller\EventController::editEvent

removeEvent:
    path: /removeEvent
    controller: App\Controller\EventController::removeEvent